### PR TITLE
Add script to generate pronoun role icons

### PR DESCRIPTION
**Pull request by michael-kenzel**

### CODE REVIEW

**Comment by claremacrae** [comment]
Did you mean to close it? It looks good to me!

**Comment by michael-kenzel** [comment]
Yeah, I noticed there is a general problem with the handling of colors by the cairosvg library I was using (it seems to not deal with sRGB correctly). I would like to still try fix that in the evening and then either reopen or create a new pull request.

**Comment by claremacrae** [comment]
That’s fine…

(It really is fine, but another time, optionally please feel free to leave an original PR open, and then open a second one after the fox - just because the history might be useful for people maintaining the file in future…)

**Comment by michael-kenzel** [comment]
Oh I can just reopen this PR and add my changes on top of the original commit if you'd prefer that.

**Comment by claremacrae** [comment]
Whatever ever’s easier for you at this point!

**Pull request closed without merging**
